### ISSUE TITLE
Option - crossair size is not activated on QGis startup

### ISSUE THREAD

**Issue by patricev** [gam17/QAD#10]
Hi, 
Just a tiny bug : the cross hair size defined within the options is not activated when loading QGis the first time (and maybe other options are not activated). You need to go to options and the apply to take effect. 
It should be great if this option works directly on qgis startup

Thanks !

**Comment by gam17** [comment]
hi Patrice,
   thank you very much for your issue. I checked and now it is fixed. In the next release of qad it will be corrected !
bye
