### ISSUE TITLE
Custom coordinate reference system is not supported

### ISSUE THREAD

**Issue by AndreyMai** [gam17/QAD#11]
Plugin working incorrectly when QGis project have a user defined coordinate reference system. Like "USER:100000".
In this case QGis show the Coordinate Reference System Selector dialog on every action on the map.
I found out that QGis Api does not understand SRS format started with "USER..." (see the [link](http://qgis.org/api/classQgsCoordinateReferenceSystem.html#a50be71ef85725c7a3959f780ac7c36cfabc92b4ee3c6be188b5dfe000ddac415e))

I found temporary solution for this. In the file "qad\qad_cacheareas.py" i replaced the line 62:
`str = str + string.replace(self.layer.crs().authid(), "USER:", "INTERNAL:")`

This code will replace SRS "USER:100000" on "INTERNAL:100000".

**Comment by gam17** [comment]
you are right !
I decided to change my code in this way:
      str = getStrLayerGeomType(self.layer)
      str = str + "?crs="
      #str = str + self.layer.crs().authid()
      str = str + self.layer.crs().toWkt()
      str = str + "&index=yes"

in the next few days you can find a new qad realease ready to download from qgis plugin site or plugin manager.
Thank you for collaborating to improve qad !
