### ISSUE TITLE
Explain fork situation

### ISSUE THREAD

**Issue by mbernasocchi** [gam17/QAD#12]
Hi, could you explain which is the active plugin codebase?
gam17/QAD is the one linked in the QGIS repo
but it is forked from geosim/QAD and gam17:master branch is 12 commits ahead, 14 commits behind geosim:master.

so apparently the two codebases are diverging?

thanks for an explaination

**Comment by gam17** [comment]
Hi Marco,
    the active plugin codebase is gam17/QAD as you can see in the QGIS 
repository.
The plugin is created by geosim but not published by it for copyright 
reasons.
Look at https://github.com/geosim/QAD/issues/11

feel free to ask for new request or to report some bugs

thanks for your interest e for making QAD a better plugin

gam17

> Hi, could you explain which is the active plugin codebase?
> gam17/QAD is the one linked in the QGIS repo
> but it is forked from geosim/QAD and This branch is 12 commits ahead,
> 14 commits behind geosim:master.
> 
> so apparently the two codebases are diverging?
> 
> thanks for an explaination
