### ISSUE TITLE
Problems when duplicating dimensioning layers

### ISSUE THREAD

**Issue by Benni5K** [gam17/QAD#13]
First, thanks a lot @geosim for creating this great plugin and @gam17 for sharing it on official repo and bringing it ahead! 

While working with the dimensioning-tool (QGIS 2.16.2, latest QAD from official repo, Windows 7 Professional), I found a problem. I understand that I need to use certain layer styling in the dimensioning-layers so that the dimensioning tool works right. For creating a map styling for a WMS I would like to use different styling for the created dimensioning geometries (geometry generated, labeling the lines not the textual layer ASO). My idea was to have three layers for creating the dimensioning (dim_line, dim_text, dim_symbol) and a duplicate for styling (same source, different layer names: dim_line_style, dim_text_style, dim_symb_style). 
But as soon as the duplicate layers are in the project, I get the 'The dimension style "test" has not the textual layer for dimension' error. My workflow in short:
- Create tables on PostgreSQL/PostGIS localhost as described in help
- Create new QGIS project, load PostGIS-Layers, style layers as described in help
- Create dimensioning style, draw some dimensionings, everything works perfect
- Create layer duplicates, style with different styling methods
- Safe QGIS project, close, reopen
- Now, when I try to draw dimensioning or change dimensioning style, error occurs

The same happens when I create views on tables on PostGIS and load them. Seems as soon as there are layers with same data structure, the plugin struggles.

If found a workaround by creating a second QGIS project with advanced dimensioning styling, load it into actual project via "embed layers and groups" and delete it, before creating new dimensionings, load it again afterwards. But would be nice if it would all work in one project. Thanks!

Best regards
Benni

**Comment by gam17** [comment]
Hi Benni,
   it's a bug ! I'am working on it... Before publishing may I send you a zip file containing the plugin so you can test it ? thank you for making QAD a better plugin !

**Comment by Benni5K** [comment]
Thanks for your fast reply! Yes of course I'm very happy to test it! 
I'm working with QAD during my masters thesis. I evaluate if QGIS with QAD can substitute comercial CAD usagein utility management. Therefore I'm interested in learning more about the background of QAD. May I ask you some questions about that? If you want, just write me an email: benni5er[a]gmx.de
Thank you very much for your help!

**Comment by gam17** [comment]
Of course! Consider that I don't know the author of QAD, I only forked his github repository to public QAD on QGIS environment. For technical questions there aren't any problems... Write me here.
bye

**Comment by Benni5K** [comment]
Hi, in the first place, I have more questions about business background, legal situation (similarity with AutoCAD), current usage in industry etc. I contacted @geosim for that. But if it comes to technical questions, I'm glad to contact you. Thanks a lot!

**Comment by Benni5K** [comment]
Thanks again for sending me the zip to test!
Duplicates of dimensioning-layers work perfect now. I tested it with several copies of dim-layers and with additional layers from different source but same data model. 
I just found one little thing independent of the actual issue. When I open a project for dimensioning and initially use DIMALIGNED/DIMLINEAR/DIMARC, I get the "The dimension style "simplex" has the textual layer (dim_qad_text_) not editable." error. I have to open the DIMSTYLE Menue first, change nothing, click 'Close', then everything works perfect. Thats a really minor problem, once you know how to handle it. Maybe changing error message to "Please choose dimensioning style first." or something like that would be enough to make it even more user friendly. If you want, I can move this to a new issue, but for me it's absolutely fine if you consider it as not so important.

**Comment by gam17** [comment]
Hi,
   that's because the layer is not editable, you can set as editable using the toolbar
![immagine](https://cloud.githubusercontent.com/assets/16491905/24121685/75eb806e-0db9-11e7-86b8-f2f9251a7aa5.png) or the SETCURRUPDATEABLELAYERBYGRAPH command.
DIMSTYLE indirectly do the same beacuse the need to show a dimensions preview.

**Comment by Benni5K** [comment]
Absolutely makes sense! Sorry, didn't consider that layers of course must be editable. Thank you again for working on it!

**Comment by Benni5K** [comment]
Hi, 
sorry, I found another error with duplicate dimensioning layers that I didn't recognise with my former test cases. 
I create the three layers for dimensioning as described in the documentation. Dimensioning and dimension styles work perfect. Then I duplicate the three layers, everything still perfect.
But as soon as I select layer style 'rule based' in one of the duplicate point layers (symbol or text), I get the following error when I want to modify the dimensioning style: 
![qad_dup_layers](https://cloud.githubusercontent.com/assets/25839469/25528081/2d36aad4-2c1c-11e7-9ed5-51f8705bed25.JPG)
It doesn't matter if there is actually a rule defined in rule based rendering or not, as soon as 'rule based' it is activated, the error occurs. Creating dimensionings isn't affected at all. Rule based styling in line layer makes no problems at all.

Let me know if you need further information or data! Thank you very much!

Regards
Benjamin

**Comment by gam17** [comment]
Hi benjamin,
   this error is due to the api change from qgis 2.12. Now it is fixed but you can use this new version olny with qgis version >= 2.12
As usual, rename the files whose terminate with ".py.txt" to ".py" only and copy them to qad installation folder.

[qad.py.txt](https://github.com/gam17/QAD/files/977047/qad.py.txt)
[qad_layer.py.txt](https://github.com/gam17/QAD/files/977049/qad_layer.py.txt)
[qad_utils.py.txt](https://github.com/gam17/QAD/files/977048/qad_utils.py.txt)
[__init__.py.txt](https://github.com/gam17/QAD/files/977050/__init__.py.txt)

I have another issue related to offset command (you are not the author). Anyway, do you get any errors using offset qad command ?

**Comment by Benni5K** [comment]
Hi,
tested in 2.16.2 and 2.18.5, works perfect now! Thanks for fixing!
Regarding OFFSET I didn't get any errors yet. Only thing to mention is that QGIS/QAD gets very slow when using OFFSET on complex geometrys with many vertices. By the way, I have the same experience with snapping when many geometries are vissible in map canvas. Seems that on the fly calculation of snapping points or OFFEST-results may be the problem. QGIS native snapping does a initial indexing, maybe thats a good solution for QAD as well.
Anyway, if you give me more details about the issue with OFFSET, I'll try to reproduce.
Regards
Benjamin
