### ISSUE TITLE
Traceback when moving circle in a linestring layer

### ISSUE THREAD

**Issue by Benni5K** [gam17/QAD#16]
I create a circle in a linestring layer with CIRCLE. Then I want to move it by mouse by clicking the center point. When I spicify new center point by click, the attached traceback occurs.
 ![traceback_qad](https://cloud.githubusercontent.com/assets/25839469/25520278/ab712238-2bfb-11e7-8bee-ba0380f5171a.JPG) 
With arc segments created with ARC it works to move them the way described above. Moving with MOVE works for both.
If I can help with further information or data, please let me know. And of course I'm allways up to test!

Regards
Benjamin

**Comment by gam17** [comment]
That's a bug !
Simple to fix, download the attached txt file, change the extension from .txt to .py and overwrite the previous version of that file with this new one in the QAD installation folder.

[qad_utils.txt](https://github.com/gam17/QAD/files/964482/qad_utils.txt)

let me know if it's ok...

**Comment by Benni5K** [comment]
Now it works! Great, thanks for fixing it!
