### ISSUE TITLE
No Edge Handles

### ISSUE THREAD

**Issue by Benni5K** [gam17/QAD#17]
Hi, 
I just realized that I don’t have handles on the edges of polygons and I think that in an earlier version of QAD there where handles to move polygon edges. Maybe I’m completely wrong anyway. I attached two screenshots, first how it looks currently, second how I think it was in earlier versions.
Regards
Benjamin

![no_edge_handle](https://cloud.githubusercontent.com/assets/25839469/26672860/0d57de86-46bb-11e7-8c59-50c101ea79fa.jpg)
![edge_handle](https://cloud.githubusercontent.com/assets/25839469/26672861/0d5b6858-46bb-11e7-9587-efb597e11d44.JPG)

**Comment by gam17** [comment]
Hi Benjamin,
   look at GRIPS sistem variable. 

It controls the use of selection set grips for the Stretch, Move,
Rotate, Scale, and Mirror Grip modes.
0 = Hides grips.
1 = Displays grips.
2 = Displays additional midpoint grips on polyline segments.

Type "grips" on the command window and set the value 2.
If QAD doesn't change the grip display mode it may be a bug...
Let me know.
bye
gam17

**Comment by Benni5K** [comment]
Perfect, GRIPS did it! Thank you for your help!
