### ISSUE TITLE
Could not open Help QAD manual on Windows 10 

### ISSUE THREAD

**Issue by NMItools** [gam17/QAD#18]
Thanks for this awesome plugin I've discovered today!

After I tried it on Windows 7 machine all worked well. 
But when I tried to open a HELP on a Windows 10 machine I got next:

```
Traceback (most recent call last):
File "C:/Users/Nebojsal.qgisZ/python/plugins\qad\qad_commands.py", line
283, in run
if self.actualCommand.run() == True: # comando terminato

File "Cz/Users/Nebojsal.qgisZ/python/plugins\qad\qad_help_cmd.py", line 63,
in run
qadShowPluginHelp() 

File "C2/Users/Nebojsal.qgisZ/python/plugins\qad\qad_msg.py", line 116, in
qadShowPluginHelp
with OpenKey(HKEY_CURRENT_USER, r"Software\Classes\http\shell\open\command") as key:
WindowsError: [Error 2] The system cannot find the file specified
MS-Windows 05 system call failed.
```

Probably the reg key for a default browser is somewhere else in Windows 10?

**Comment by gam17** [comment]
QAD looks for the default browser only in current user registry environment.
May be that in your PC it doesn' exist and it is defined at machine level and not at user level.
I have changed the QAD code. Now, it looks in HKEY_CURRENT_USER first and if it fails looks in HKEY_LOCAL_MACHINE.
Rename the attached file in qad_msg.py and overwrite the existing file in the QAD installation folder.
If you need help about QAD commands, remeber that almost all QAD command are similar to autocad commands so you can google "<command name> autocad command " (for example for pline command "pline autocad command")
Let me know if it is fixed.
bye
gam18
[qad_msg.txt](https://github.com/gam17/QAD/files/1061000/qad_msg.txt)

**Comment by NMItools** [comment]
I did what you suggested.
It opens with Internet Explorer but not with default browser in the system.
