### ISSUE TITLE
qad_cacheareas.py TypeError

### ISSUE THREAD

**Issue by techdude1996** [gam17/QAD#19]
I get this error whenever I try to do anything with QAD enabled. It is complaining about qad_cacheareas.py line 61
`60    str = getStrLayerGeomType(self.layer)`
`61    str = str + "?crs="`
Where `str` is initially nothing on line 61.
I have the First-Aid plugin enabled so nothing crashes, but the TypeError window shows up everytime I do something that QAD isn't in charge of. When I try to select a polygon for editing, I get an error message (not from the First-Aid plugin) that gives the same error. This seems like an awesome plugin, but I haven't been able to use it yet due to this error.

Here is the First-Aid error:
![capture2](https://user-images.githubusercontent.com/25308291/28838624-e5b12836-76be-11e7-8623-186d0d3c6685.PNG)

Here is the QGIS Error:
![capture3](https://user-images.githubusercontent.com/25308291/28838652-f63e08f4-76be-11e7-8034-ff336d8e972e.PNG)

Thank you for your time

**Comment by gam17** [comment]
Hi techdude1996,
   can you send me a qgis project with same sample data? I want to reproduce the error.
Probably you are working with some vector layer whose geometry type is not in the conditions considered by the QAD function:

def getStrLayerGeomType(layer):
   wkbType = layer.wkbType()
   if wkbType == QGis.WKBPoint:
      return "Point"
   elif wkbType == QGis.WKBMultiPoint:
      return "MultiPoint"
   elif wkbType == QGis.WKBLineString:
      return "LineString"
   elif wkbType == QGis.WKBMultiLineString:
      return "MultiLineString"
   elif wkbType == QGis.WKBPolygon:
      return "Polygon"
   elif wkbType == QGis.WKBMultiPolygon:
      return "MultiPolygon"


Waiting for your data...
bye 
gam17

**Comment by techdude1996** [comment]
I'm using QGIS 2.18.10
Here is a shapefile that causes the issue.
I also found out that OSM and Open Layers plugins both cause this issue as well. Just removing the web layers fixes the issue. I am using standard geometry: polygons not multi-polygons.
[Property.zip](https://github.com/gam17/QAD/files/1208591/Property.zip)

**Comment by gam17** [comment]
I found the problem: tha shape you sent me contains WKBPolygon25D
geometries.
QAD support only 2D geometries (in this case WKBPolygon). I am working
to support WKBPoint25D, WKBMultiPoint25D, WKBMultiLineString25D,
WKBPolygon25D and WKBMultiPolygon25D geometry types.
Wait for the next QAD version...
Thanks for making QAD a better plugin !
gam17

**Comment by techdude1996** [comment]
How to I convert it to 2D geometries?

**Comment by techdude1996** [comment]
Found the solution to convert geometry type:
1. Save the layer as -> Geometry -> uncheck "Include z-dimension"

**Comment by gam17** [comment]
well done !
