### ISSUE TITLE
Avoid binary attachments

### ISSUE THREAD

**Issue by pcav** [gam17/QAD#2]
The docx file should be replaced with srt documentation, in coherence with all the qgis docs. pandoc may be your friend here.

**Comment by gam17** [comment]
Il 2016-04-13 15:21 Paolo Cavallini ha scritto:
> The docx file should be replaced with srt documentation, in coherence
> with all the qgis docs. pandoc may be your friend here.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gam17/QAD/issues/2
I removed docx file, it was a developing note not important for final 
user.
I corrected the metadata.txt file too.
Hope it is right now.
thanks
