### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'COMMIT_BY_INTERNAL'


### ISSUE THREAD

**Issue by peter-shr** [gam17/QAD#20]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/USER/.qgis2/python/plugins\qad\qad.py", line 1254, in beforeCommitChanges
    if self.layerStatusList.getStatus(layer.id()) != QadLayerStatusEnum.COMMIT_BY_INTERNAL:
AttributeError: 'NoneType' object has no attribute 'COMMIT_BY_INTERNAL'

```
qad 2.14.2, QGIS 2.14.17-Essen on Windows 10

**Comment by gam17** [comment]
Hi Peter,
   can you report the steps to reproduce the error please ?
Thanks
gam17

**Comment by gam17** [comment]
After waiting for an answer I have decided to close this issue.

**Comment by peter-shr** [comment]
Hello gam17/QAD,
Sorry for the very late answer, but at the end of the year it is always very strenuous.
I have been working with the latest version for the last two days. Everything's been going very well so far. 
(QGIS 2.18.15)

With best regards, Peter
(translated with www.deepl.com) 
 

    Am Freitag, 29. Dezember 2017, 18:43:56 MEZ hat gam17 <notifications@github.com> Folgendes geschrieben:  
 
 
After waiting for an answer I have decided to close this issue.
