### ISSUE TITLE
Error trying to move with snaps on

### ISSUE THREAD

**Issue by twomdid** [gam17/QAD#23]
Getting a very similar error to the other issues - it happens if I try to move while any snaps are enabled, and I can't perform the move action.

![image](https://user-images.githubusercontent.com/34284554/33627223-38290b98-d9d3-11e7-8608-743bb0a1569a.png)

**Comment by gam17** [comment]
Hi,
   have you seen the issue on  https://github.com/gam17/QAD/issues/19 ?
Is it the same situation ?
If not, can you send me a qgis project with same sample data? I want to
reproduce the error.
bye
gam17

**Comment by gam17** [comment]
After waiting for an answer I have decided to close this issue.
