### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by All4Gis** [gam17/QAD#28]
I'm looking at the code and I have a question, why do there exist so many differences between the master branch and the version published in QGIS?

For example, the file qad_dynamicinput.py does not exist in master and many other changes.

What is the latest stable version?2.14.4?
https://plugins.qgis.org/plugins/qad/

**Comment by gam17** [comment]
Hi Fran,
   you are right ! When I published the 2 last QAD versions I forgot to
copy the plugin code in github repository...
Please use the version published in QGIS repository.
Sorry for the inconvenience...

gam17
