### ISSUE TITLE
Option popup should have minsize

### ISSUE THREAD

**Issue by pcav** [gam17/QAD#3]
Currently it can be shrunk to 0 width.
When enlarged, the box inside stay fixed.
Be careful also about text: in gnome3 at least, it is larger then the box containing it.
Thanks.

**Comment by gam17** [comment]
Corrected !
The problem was in italian localization only...
How can I upload the corrections ?

**Comment by pcav** [comment]
Thanks. Please publish a new version. If you let me know when done, I'll try to approve it ASAP.

**Comment by gam17** [comment]
published
