### ISSUE TITLE
COPY command gives error

### ISSUE THREAD

**Issue by jaitor1** [gam17/QAD#30]
![image](https://user-images.githubusercontent.com/12136796/72814797-f780d380-3c65-11ea-8a7a-1204c12e6424.png)

How to reproce it:

![screen](https://user-images.githubusercontent.com/12136796/72814977-3e6ec900-3c66-11ea-87d9-5bea5c18ee57.gif)

**Comment by gam17** [comment]
download and let me know
gam17
