### ISSUE TITLE
DIVIDE command gives error

### ISSUE THREAD

**Issue by jaitor1** [gam17/QAD#31]
![image](https://user-images.githubusercontent.com/12136796/72815436-ef756380-3c66-11ea-8cf3-6a2dff0e2720.png)

How to reprocude it:

![screen2](https://user-images.githubusercontent.com/12136796/72815390-df5d8400-3c66-11ea-869c-9ef1214243b6.gif)

**Comment by gam17** [comment]
download and let me know
gam17

**Comment by jaitor1** [comment]
Now it works!
