### ISSUE TITLE
"Right-click customization" settings not saved

### ISSUE THREAD

**Issue by gabriel-de-luca** [gam17/QAD#34]
In _"Options ~> User Preferences ~> Right-click customization"_ I want to use the following settings:  

![RightclickCustomization](https://user-images.githubusercontent.com/48416462/73612561-8fb67b00-45cb-11ea-8225-108110ab2efb.png)

Even if I click _"Apply&Close"_, when I see the options again, they remain the same default ones.

**Comment by gam17** [comment]
Hi Gabriel,
download the new version from github and let me know
gam17

**Comment by gabriel-de-luca** [comment]
Hi @gam17 ,
 It works now. Thank you!
