### ISSUE TITLE
HELP command does nothing.

### ISSUE THREAD

**Issue by gabriel-de-luca** [gam17/QAD#38]
I have seen the previous issue: https://github.com/gam17/QAD/issues/18, also: https://github.com/gam17/QAD/issues/4.  

Since I have installed the plugin via ZIP file, I cannot edit the qad_msg.py file as suggested in the Issue #18 . About the issue #4, I don't know how to access the rst files.  

I am working in a Windows 10 machine and the HELP command does nothing. If an Internet page must be opened, may be enough for me if the commands text window returns the URL.

**Comment by gam17** [comment]
It seems fixed. Reopen this issued if you have any problem. 
Thank you for making qad a better plugin
gam17
