### ISSUE TITLE
Installing QAD causes a crash of QGis

### ISSUE THREAD

**Issue by dd-a** [gam17/QAD#40]
QAD v 3.0, QGis 3.10.3 and 3.12.0, Mac OS 10.15.3 .

Moreover restarting QGis causes a new crash.  I had to remove QAD manually from the plugins folder to have QGis starting correctly.

**Comment by gam17** [comment]
Hi dd-a,
   I am sorry for the problem you had with QAD.
To be honest the QAD tester team didn't test QAD on Mac.
Can you help me to understand this bug ?
Is there any error message ?
Any information may be useful...

Thanks for making QAD a better plugin

gam17

**Comment by dd-a** [comment]
Hello !
Unfortunately I didn't find any error message in the message center.  I see that the crash occurs while the installation mentions "téléchargements de données" (meaning "download of data").  I'm afraid this is not very helpful...
If you think of anything specific I should look at, just ask !

**Comment by marcobra** [comment]
Same here on qgis
Versione di QGIS | 3.12.0-București | Revisione codice QGIS | 409bcf8eaa

Compilato con Qt | 5.9.5 | Esecuzione con Qt | 5.9.5
Compilato con GDAL/OGR | 2.2.3 | Esecuzione con GDAL/OGR | 2.2.3
Compilato con GEOS | 3.6.2-CAPI-1.10.2 | Esecuzione con GEOS | 3.7.1-CAPI-1.11.1 27a5e771
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
Versione client PostgreSQL | 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) | Versione SpatiaLite | 4.3.0a
Versione QWT | 6.1.3 | Versione QScintilla2 | 2.10.2
Versione PROJ.4 | 493
OS Version | Ubuntu 18.04.4 LTS

Running from command line give this errors at startup and qgis crash: 


Warning: QFileInfo::absolutePath: Constructed with empty filename
Warning: QFileInfo::absolutePath: Constructed with empty filename
Exception ignored in: <bound method QadMBUFFERCommandClass.__del__ of <qad.cmd.qad_mbuffer_cmd.QadMBUFFERCommandClass object at 0x7f026203a168>>
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/cmd/qad_mbuffer_cmd.py", line 83, in __del__
    del SSGetClass
UnboundLocalError: local variable 'SSGetClass' referenced before assignment
Exception ignored in: <bound method QadMBUFFERCommandClass.__del__ of <qad.cmd.qad_mbuffer_cmd.QadMBUFFERCommandClass object at 0x7f0261f9bf78>>
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/cmd/qad_mbuffer_cmd.py", line 83, in __del__
    del SSGetClass
UnboundLocalError: local variable 'SSGetClass' referenced before assignment
QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operazione non permessa.
No thread selected
No stack.
gdb returned 0
Annullato (core dump creato)

**Comment by gam17** [comment]
Hi,
   looking at

File "/home/ubuntu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qad/cmd/qad_mbuffer_cmd.py", line 83, in del
del SSGetClass

I found and fixed an error. Can you substitute the qad_mbuffer_cmd.py with the attached file ?
Before substituting it you have to rename the new file from qad_mbuffer_cmd.py.txt to qad_mbuffer_cmd.py.
hope it solves.
waiting for news
gam17
[qad_mbuffer_cmd.py.txt](https://github.com/gam17/QAD/files/4291569/qad_mbuffer_cmd.py.txt)

**Comment by dd-a** [comment]
Unfortunately, that didn't solve the problem.  Same crash, sorry.

**Comment by marcobra** [comment]
Do not solve...

Thread 1 "qgis.bin" received signal SIGSEGV, Segmentation fault.
0x00007ffff491a083 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff491a083 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff491ac52 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff491ae4e in QColorDialog::changeEvent(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007fff476fd783 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so
#4  0x00007ffff4775424 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007fff476dbd53 in  () at /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-36m-x86_64-linux-gnu.so
#6  0x00007ffff473683c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff473e104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff56343db in QgsApplication::notify(QObject*, QEvent*) () at /usr/lib/libqgis_core.so.3.12.0
#9  0x00007ffff39b88d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff39bb04d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff3a12263 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007fffe797e417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fffe797e650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007fffe797e6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff3a1188f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff74112be in QgisApp::QgisApp(QSplashScreen*, bool, bool, QString const&, QString const&, QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/libqgis_app.so.3.12.0
#17 0x000055555555dd0e in  ()
#18 0x00007ffff2dbdb97 in __libc_start_main (main=
    0x55555555bd10, argc=1, argv=0x7fffffffde58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde48) at ../csu/libc-start.c:310
#19 0x00005555555617fa in _start ()
(gdb)

**Comment by M-Rick** [comment]
I have QAD running in QGIS 3.10.4 under Catalina and it's not crashing.
It's maybe a conflict with other extensions.
The way to know is to remove manually all your extensions from the QGIS settings  python extension folder. Then you add them one-by-one. Try first with QAD.
Try to remove the cash folder inside the QGIS settings folder as well.

**Comment by dd-a** [comment]
Sorry @M-Rick, I didn't see your message.  
You were right! I found that the incompatibility is with the [QDraw](https://github.com/jeremyk6/qdraw/) plugin.
