### ISSUE TITLE
QAD text window not removed when plugin is disabled

### ISSUE THREAD

**Issue by mstuyts** [gam17/QAD#42]
When the plugin is unchecked in the "Plugins management" window of QGIS, the "QAD text window" panel remains visible and is still available in the Panels selection list of QGIS.  All other QAD toolbars and panels are no longer available as it should be.

Tested on QGIS 3.12.0 on Windows 10.

**Comment by gam17** [comment]
Hi Michel,
   I'm sorry I can't reproduce the bug. I'm using QGIS 3.4.11-Madeira on
windows 8.
As soon as possible I will test the bug using your QAD version and s.o.

Thanks to make QAD a better plugin

gam17

**Comment by mstuyts** [comment]
I'm sorry. I mixed up two things.  When the plugin is disabled and enabled in Plugin Management, it works just fine.  

I was using the "Plugin Reloader" plugin to disable and enable it, because I was looking into bug #38. If I reload QAD, the QAD text window shows up multiple times, because it's not unloaded.  It could be a bug in the "Plugin Reloader" plugin, but all other QAD panels and toolbars get unloaded when reloading QAD this way.

**Comment by gam17** [comment]
dowanload and try, please.
let me know...
gam17

**Comment by mstuyts** [comment]
I downloaded the files from this repository and tested it in QGIS.  Now it works as expected.  Thanks for the quick solution.
