### ISSUE TITLE
DIMLINEAR and DIMALIGNED don't work in Object mode

### ISSUE THREAD

**Issue by gabriel-de-luca** [gam17/QAD#46]
Hi gam17,

 I was trying to dimension an object, with DIMLINEAR and DIMALIGNED, but in the Object mode, when I select a feature geometry, a window pops up with the following error:

```
Well, this is embarrassing !

Name not found globally.
NameError: name 'getQadGeomPartAt' is not defined
  File "C:/Users/Gabriel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\cmd\qad_dim_cmd.py", line 666, in run
    g = getQadGeomPartAt(g, res[2], res[3], res[4])
  File "C:/Users/Gabriel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_commands.py", line 337, in continueCommandFromMapTool
    if self.actualCommand.run(True) == True: # comando terminato
```

I'm using QAD 3.0.2, on QGIS 3.12.2. I have tested it in LineString and MultiLineString layers, with lines of one or more segmentes and with multilines with one or more parts, in temporary scratch, GeoPackage and shapefile layers.

Kind Regards,
Gabriel

**Comment by gam17** [comment]
Hi Gabriel,
   I think it is fixed now. Download, try ad let me know, please...

Thanks for making qad a better plugin

gam17

De Luca ha scritto:

**Comment by gabriel-de-luca** [comment]
Hi gam17, 

Yes, it works fine now.

Thanks to you!

Gabriel
