### ISSUE TITLE
Deselected polygons

### ISSUE THREAD

**Issue by reancris** [gam17/QAD#47]
Hi, sorry if you find any misspelled spelling, it's because I used a translator. I installed the plugin in version 2.8, and the polygons remain selected and I can use the plugin tools. but in version 3.10, I select a polygon, I approach the vertices and that polygon is deselected. Attached gif of what happens.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6498018/88622384-56d1fd00-d068-11ea-8f5b-efb4c6665290.gif)

I don't know if I'm doing something wrong, or it's a version error.

I appreciate your help with developing the plugin, and collaborating with the world.

**Comment by gam17** [comment]
Hi reancris !
thank you for reporting this issue, Can you download and try ?
gam17

**Comment by reancris** [comment]
Thank you very much, I have tested the plugin and it is working fine. I wait when this is the distribution of the QGIS plugin manager
