### ISSUE TITLE
NameError: name 'QadVariable' is not defined

### ISSUE THREAD

**Issue by sdnxgr** [gam17/QAD#48]
Encountered when changing drafting tool config (e.g. colors, etc.). Python path or other plugin conflict?
QAD v 3.0.2

NameError: name 'QadVariable' is not defined

Traceback (most recent call last):
  File "C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python/plugins\qad\qad_windowcolor_dlg.py", line 397, in Button_ApplyClose_Pressed
    variables = self.getSysVariableList()
  File "C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python/plugins\qad\qad_windowcolor_dlg.py", line 391, in getSysVariableList
    variables.append(QadVariable(varName, varValue, QadVariableTypeEnum.COLOR))
NameError: name 'QadVariable' is not defined

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.4-A Coruña A Coruña, 10bc9f2ff2 

Python Path:
C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python/plugins\curve_number_generator
C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python/plugins\csv_tools
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python
C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Owner/AppData/Roaming/QGIS/QGIS3\profiles\ SGR/python
C:\Users\Owner\AppData\Roaming\QGIS\QGIS3\profiles\ SGR\python\plugins\mmqgis/forms

**Comment by gam17** [comment]
Hi sdnxgr !
thank you for reporting this issue, Can you download and try ?
gam17

**Comment by sdnxgr** [comment]
Reinstalled plugin from manager, if that's what you meant.
No change in behavior

**Comment by sdnxgr** [comment]
Also tried in default profile.
No change in error.

**Comment by reancris** [comment]
Hello, download the plugin from this repository, not from qgis plugin manager

**Comment by gam17** [comment]
As reancris wrote, try to download the fixed code from github. This is because I want to be sure the error is really fixed before distrubuting a new QAD release by qgis repository. Let me know if you have problem to download and install the plugin.

**Comment by sdnxgr** [comment]
Yes indeed, that worked. Thank you.
