### ISSUE TITLE
Follow QGIS's snap settings

### ISSUE THREAD

**Issue by olivierdalang** [gam17/QAD#49]
@gam17 

Hi and thanks for the great plugin !

To make drawing more efficient, we would be interested in making the plugin take QGIS's snap settings into account.

As a first step, I suggest to only use the layer settings (`current layer`, `all layers`, or `custom`), but continue to use the plugin's snap types (simply ignoring QGIS's snap types, because it's not possible to clearly match QGIS's snap types with QAD's snap types).

What do you think ?

I had a quick look at the code, and think I could work on a pull request if you like the idea. I just prefer to ask before doing the work just in case you have other/better ideas !

Cheers,

Olivier

**Comment by gam17** [comment]
Hi Olivier,
   QAD doesn't consider the QGIS snap settings because it clones the
Autocad logic.
I like your idea so you can work on a pull request.
In this period I have no time to work on QAD but if you need help
doesn't esitate to write me.
Thanks to make QAD a better plugin!
bye
gam17
