### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'showEvent'


### ISSUE THREAD

**Issue by pigreco** [gam17/QAD#5]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/Salvatore/.qgis2/python/plugins\qad\qad_textwindow.py", line 176, in showEvent
    QDockWidget.showEvent(self, e)
AttributeError: 'NoneType' object has no attribute 'showEvent'

```
qad 2.8.010, QGIS 2.15.0-Master on Windows 10

**Comment by gam17** [comment]
can you explain how to reproduce this error step by step ?
thanks for collaboration
gam17

**Comment by pigreco** [comment]
I just installed the plugin Reports Plugins and after the upgrade of QAD PLUGIN appeared an error and is automatically started the plugin Reports.
sorry

**Comment by gam17** [comment]
I can't reproduce the error. I am sorry. I don't understand the reason of that.
Let me know if the problem persist uninstalling Report Plugin.

**Comment by gam17** [comment]
I will close this issue because it is long time you don't update this issue. Feel free to reopen if you have some news.
