### ISSUE TITLE
QAD Plugin Issue

### ISSUE THREAD

**Issue by CamiloCorredor** [gam17/QAD#50]
s QAD compatible with QGIS 3.14 "Pi"?

I've several issues with it.

Rotate, simetry, etc, does not work

is convenient downgrade QGIS 3.14 to versión 2.X?

Thanks, 

[Files-QAD.zip](https://github.com/gam17/QAD/files/5188536/Files-QAD.zip)
![Captura de pantalla de 2020-09-07 21-51-30](https://user-images.githubusercontent.com/70957642/92482857-ba922e80-f1ad-11ea-87b4-fe87ae52907c.png)

**Comment by gam17** [comment]
Can you download from github and try ? let me know if it is fixed...
gam17

**Comment by CamiloCorredor** [comment]
Excuse me, download the plugin? 

I don't understand as well

**Comment by CamiloCorredor** [comment]
It's fixed! 
The points rotates in the current project!
Thank u!
