### ISSUE TITLE
Customization Request

### ISSUE THREAD

**Issue by ahmadza104** [gam17/QAD#52]
Hello GAM17,

I'm working on a GIS project to digitize electricity distribution network. Your QAD plug-in is a fantastic tool for my project.

Can I engage your service to customize the QAD to add few more features?

Features that we want to add:-

1. Auto-Create a few line (like 4,5,6,7,8 lines) from a single point (like a fork) where the first and last angle should not exceed a certain angle (like 60 degree) AND auto snap to a pre-defined point.

2. Auto-Create a line with a gap of 1 meter line from a selected pole.
 
3. Auto-Create 1 meter parallel lines (like 2,3,4 or 5 lines) with a fixed gap (like 0.3 meter and 0.5 meter)

4. Auto-create a point near the edge of a selected line. The point on that selected line shall be positioned 2.5 meter from the nearest pole.

I appreciate if you can assist.

ahmad104 gmail com

**Comment by gam17** [comment]
HI ahmadza104,
   I think it is possible to develope a plugin which can use QAD as
command library.
If you are a developer I can assist to point to the functions you have
to use in QAD library.
If you want a plugin ready to use I can develope for you.
Please, just for a better understanding, can you send me some pictures
for every single command (initial status, final situation) at
gam17@riseup.net ?
I will send you an estimate development time.
Thank you
bye
gam17
