### ISSUE TITLE
Mapping key not found error

### ISSUE THREAD

**Issue by vovchykbratyk** [gam17/QAD#53]
Hi, I attempted to run a mirror of some vector content and ran into this (I guess related to PyQt4 dependencies that QGIS 3.x does not ship with):

![qad_mirror_crash](https://user-images.githubusercontent.com/40668075/93529514-052c4d00-f90a-11ea-9f22-b3f3d870a45b.PNG)

I'm on QGIS 3.14.15; Windows 10.

**Comment by gam17** [comment]
Hi vovchyk bratyk,
   can you try using the latest QAD version 3.0.4 ?
It has been published today.
Let me know if it solves...

gam17

**Comment by vovchykbratyk** [comment]
You win the award for fastest response ever!  Thanks so much, it appears to be working!
![mirror_vector_working](https://user-images.githubusercontent.com/40668075/93601720-9d204a00-f98f-11ea-949b-695dd92efdbe.PNG)
