### ISSUE TITLE
New feature: Automatic offset tool

### ISSUE THREAD

**Issue by M-Rick** [gam17/QAD#55]
QAD has an offsetting tool. But in the case there are many lines to be offset, it could a very long job to do. QAD could integer a new tool to automatically offset lines.

In order to be able to automatically offset lines, the layer should include a field with the offset values. QAD could then automatically offset lines using the value stored in that field.
QAD will display a dialog asking which field to be used as an offset value. The offset unit can be set like any other QGIS objects: millimeters, points, pixels, meters at scale, map units, inches.
There'd have another feature, the choice between working on the current layer or creating a new one.

![Capture d’écran 2020-10-23 à 15 25 38](https://user-images.githubusercontent.com/2520948/97009357-4a185480-1544-11eb-846e-a95f3ab77a38.png)

This could be achieved by 2 ways:
- The whole layer will get offset.
- The objects to be offset are selected.

If the offset field value is equal to 0 or NULL, nothing will be offset.

**Comment by gam17** [comment]
Hi M-Rick,
   thanks for your suggestion. None but you has asked for it.
If tuo need a customization you can change the code of QAD or you can consider a donation if you prefer a developer make it for you. In this case you can consider the developer comunity or me.
bye
gam17
