### ISSUE TITLE
QAD after upgrade mantains the upgradeable status

### ISSUE THREAD

**Issue by SergioGollino** [gam17/QAD#6]
After plugin upgrade QAD is still in the upgradeable list. Using "upgrade plugin" equals to reinstall it. Tested on qgis 2.14.2 and 2.14.3 (W7)

Thank you very much!

**Comment by Nicephore17** [comment]
Yes. Same for me. I think there is revision number misspell between 2.8**.010** and 2.8**.10**.

**It says** (in extension pane) :
Version installée : 2.8.010 (dans C:\Users\Nicolas\.qgis2\python\plugins\qad)
Version disponible : 2.8.10 (dans Dépôt officiel des extensions QGIS

**Comment by gam17** [comment]
In the next release I'll fix it using 2.8.11 version number.
Next in the future QAD will provide the array command with its 3 version: arrayrect, arraypath and arraypolar.
I hope you will enjoy.
If you need an autocad command not included in QAD feel free to pull a request. When a command will be asked from a great number of people I can decide to develope it.
