### ISSUE TITLE
dimension text layer not recognized

### ISSUE THREAD

**Issue by schorsch2** [gam17/QAD#60]
I have created a text layer according to the help.

`CREATE TABLE public.dim_text
(
  id serial NOT NULL,

  text character varying(50) NOT NULL,

  font character varying(50) NOT NULL,

  h_text double precision NOT NULL,

  rot double precision NOT NULL,

  color character varying(10) NOT NULL,

  dim_style character varying(50) NOT NULL,

  dim_type character varying(2) NOT NULL,

  geom geometry(Point,25833),

  dim_id bigint NOT NULL,

  CONSTRAINT dim_text_pkey PRIMARY KEY (id)

)

WITH (

  OIDS=FALSE

);

 CREATE INDEX dim_text_dim_id

  ON public.dim_text

  USING btree

  (dim_id);

 
CREATE INDEX sidx_dim_text_geom

  ON public.dim_text

  USING gist

  (geom);
 
`

![dimlayer](https://user-images.githubusercontent.com/13661057/122532552-ed146600-d020-11eb-8c43-ab309852d034.png)
This is not recognised in the settings.The other layers, which were created according to the same recipe, are recognised. What could be the reason for this?

**Comment by gam17** [comment]
Hi schorsch2,

The text layer is a layer that displays labels only. It is a QGIS point
layer with the following characteristics:
1.	the symbol must have a minimum of 90% transparency
2.	must have a label
Layers that are not textual will be considered as symbol layers.

set these properties on text field...

let me know if it works

gam17

**Comment by schorsch2** [comment]
Ok, now I understand. My problem was here:

> 1.	the symbol must have a minimum of 90% transparency

In the properties, it means setting the opacity to a maximum of 10.
It works now as expected.
Thanks!
