### ISSUE TITLE
The form to fill the data does not appear

### ISSUE THREAD

**Issue by franksalas1965** [gam17/QAD#61]
They could add the option that when the creation is finished, the form to fill the data appears as it happens with the standard drawing tools?
For example, when I use the MPOLIGONO tool, and I finish creating it, the form does not appear to fill in the data associated with that object as it happens with the standard QGis tool

**Comment by gam17** [comment]
Hi franksalas1965,
   actually QAD runs the same way as autocad does.
Are you interested on supporting this enhancement with a donation ?
bye gam17

**Comment by gam17** [comment]
Hi franksalas1965,
   I developed your idea. I spent 2 work days to modify the code.
Are you interested on supporting this enhancement with a donation ?
Let me know ...

**Comment by franksalas1965** [comment]
good evening, unfortunately I do not have the possibility to make a
donation to support the project, I sincerely would have liked to, I live in
Cuba and it is difficult for me to carry out this type of operations
Regards, Francisco
