### ISSUE TITLE
Error filtering scale based visibility vector layers

### ISSUE THREAD

**Issue by thelooka** [gam17/QAD#64]
First of all thanks for your contribution to QGIS, the plugin is so usefull and works very well.
Using the last version of your plugin and QGIS version 3.16.11, I noticed that there is an error in filtering (and snapping over) the vector layers having a "scale based" visibility.
Every time the "hasScaleBasedVisibility" condition is checked in the QAD code, there is also a control between the scale visibility of the layer and the scale of the canvas.
The error is in this second condition: since the scale is in the denominator (1:X), the minor and major signs must be reversed to obtain the desired behavior:
(self.canvas.mapSettings().scale() < layer.minimumScale() or self.canvas.mapSettings().scale() > layer.maximumScale())
must be
(self.canvas.mapSettings().scale() > layer.minimumScale() or self.canvas.mapSettings().scale() < layer.maximumScale())

I think this fix will works fine.

File to fix:
 - qad_cacheareas.py (line 347)
 - qad_utils.py (lines 903, 929)
 
Best regards

**Comment by gam17** [comment]
Thank you very much thelooka !
download from this site and let me know if now it is fixed...
Thanks for making QAD a better plugin
gam17
