### ISSUE TITLE
MPOLYGON-tool crashes when trying to use trace-function

### ISSUE THREAD

**Issue by Atol2022** [gam17/QAD#66]
I encountered a bug while using MPOLYGON-tool. When I attempt to use TRACE-function to do the polygon I immediately get a following error message: 
<img width="311" alt="image" src="https://user-images.githubusercontent.com/103053334/161782026-50b09a37-6514-4e88-9e7f-5e3293bf6fc7.png">
Tool stops functioning immediately after clicking trace and second input produces the error message above.

**Comment by gam17** [comment]
can you try using the last version in github ? I thinkI I fixed it

**Comment by gam17** [comment]
reopen this issue if the problems persists, please
