### ISSUE TITLE
Request: Ability to set amount of points on cirkles/arcs.

### ISSUE THREAD

**Issue by APOS80** [gam17/QAD#67]
When drawing circles the lines is very ruff/edgy, would be great if i could set the amount of points.

**Comment by gam17** [comment]
Hi Andreas,
   run "options" command. You can set "Maximum admitted error between a
real curve and the approximated, segmented curve" to a minor value. You
can adjust "Minimum number of segments in a circle" too.
hope it helps
bye
gam17
