### ISSUE TITLE
QgsMapCanvas.mapRenderer() is deprecated

### ISSUE THREAD

**Issue by robinpaulson** [gam17/QAD#7]
Hi, when I use QAD, I get this error a lot:
2016-07-22T17:21:58	1	warning:/home/robin/.qgis2/python/plugins/qad/qad_stretch_cmd.py:644: DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated
			  coordTransform = QgsCoordinateTransform(self.plugIn.canvas.mapRenderer().destinationCrs(), entity.layer.crs())
			
			traceback:  File "/home/robin/.qgis2/python/plugins/qad/qad_getpoint.py", line 837, in canvasPressEvent
			    self.plugIn.QadCommands.continueCommandFromMapTool()
			  File "/home/robin/.qgis2/python/plugins/qad/qad_commands.py", line 319, in continueCommandFromMapTool
			    if self.actualCommand.run(True) == True: # comando terminato
			  File "/home/robin/.qgis2/python/plugins/qad/qad_maptool.py", line 716, in run
			    res = self.currentCommand.run(msgMapTool, msg)
			  File "/home/robin/.qgis2/python/plugins/qad/qad_stretch_cmd.py", line 828, in run
			    self.stretchFeatures(value)
			  File "/home/robin/.qgis2/python/plugins/qad/qad_stretch_cmd.py", line 697, in stretchFeatures
			    if self.stretch(entity, ptList, offSetX, offSetY, tolerance2ApproxCurve) == False:
			

This is on Ubuntu 14.04, qgis 2.16.0 from the ubuntugis repo on launchpad

Python versions 3.4 and 2.7

Cheers

Everything appears to work OK, although it's annoying and slows down my system after it appears.

**Comment by robinpaulson** [comment]
I also occasionally get this error under Ubuntu Xenial as well

**Comment by gam17** [comment]
Hi, thank you for reporting this issue. The message is because api has changed and some functions are now deprecated. I found and corrected the code but the new code will run on QGIS >= 2.4 version. Now i'm using 2.8 ltr. You can wait for the next QAD release (2.13) or i can commit the changes in the github repository so you can download immediatly. Can you give me a feed back about what you like and, more important, what you don't like about QAD ? Is there some cad commands you would you like to have ?
thanks for collaborating
bye

**Comment by robinpaulson** [comment]
Sure, it would be good to get that sooner rather than later, I'm using qgis 2.16

The plugin is good, I come form a CAD background, so it's nice to see something with those users in mind. The only (very small) suggestion is to fix the layout in the QAD Options dialogue - on my system, the words are all squashed up and hard to read. Either the font should be smaller or the space for the text bigger.

Actually, it would be good to always allow the user to scroll-to-zoom, at present that doesn't happen when QAD is selected but no command is active.

Cheers for asking!

**Comment by gam17** [comment]
Strange... On my pc (windows 7) it looks like in the attached image.
![image](https://cloud.githubusercontent.com/assets/16491905/17319661/7014671c-588f-11e6-8ad5-ab847ffe6cd0.jpg)
I use qgis 2.8 and I can scroll-to-zoom when QAd is selected but no command is active.
I will try with qgis 2.16.

**Comment by robinpaulson** [comment]
Yeah, I'm using Ubuntu MATE (a derivative of GNOME) 16.04, so I'd expect to get rendering differences. Maybe there are different fonts? Also, that dialogue is way bigger than on my install.

**Comment by robinpaulson** [comment]
Hi, when do you plan to release the bug fixes? ASAP would be really great, it's making editing rather frustrating.

Cheers

**Comment by gam17** [comment]
I was on holiday. Now you can download the zip file from github site. I will wait some more corrections before public an update version on qgis plugin repository.
Sorry for the time you have been waiting...

**Comment by robinpaulson** [comment]
Cheers for the fixes, it's all working very smoothly now. Here's a screenshot to show the squashed up text I mentioned:
![screenshot from 2016-08-29 03-06-50](https://cloud.githubusercontent.com/assets/1186107/18034657/b8bfdfbc-6d31-11e6-8557-bca81103c59e.png)
