### ISSUE TITLE
Qad. Part.

### ISSUE THREAD

**Issue by pportiz** [gam17/QAD#70]
Good afternoon.
When using comand PART, it doesn´t part the line but make a copy of the designed segment and put it besides de original line. I'm running this plugging in QGis 3.22.4.
Best regards.

**Comment by gam17** [comment]
Hi,
   I suppose you are using spanish version. As PART command doesn't
exist I think you are refering to PARTE command which is named BREAK in
english version.
For future reference write the name of the command and the language you
are using, please.
I can't reproduce your error... can you send me a simple qgis project
with one line layer (shape file) e write me step by step what I have to
do to reproduce this issue.
I will happy to help you.
gam17
