### ISSUE TITLE
BUENA HERRAMIENTA

### ISSUE THREAD

**Issue by jmgl0003** [gam17/QAD#72]
La herramienta se puede mejorar pero es perfecta. Si tenéis alguna cuenta para donar y seguir desarrollándola decírmelo.

Gracias

**Comment by gam17** [comment]
Hi jmgl0003 !
   after more than 120000 downloads this is the first time someone wants support me ! 
Thank you very much ! If you want to donate please use the following paypal link:
https://paypal.me/qadforqgis?country.x=IT&locale.x=en_US
