### ISSUE TITLE
Polar tracking not working

### ISSUE THREAD

**Issue by MUYUM** [gam17/QAD#73]
Hi

I've set POLARMODE to 11:

Polar angle measurements
0 = Measure polar angles based on current UCS (absolute)
**1 = Measure polar angles from selected objects (relative)**
Object snap tracking
0 = Track orthogonally only
**2 = Use polar tracking settings in object snap tracking**
Acquire object snap tracking points
0 = Acquire automatically
**8 = Press Shift to acquire**

Then I have used PLINE to draw polyline. After first segment is drawn, I would expect, that when holding "SHIFT" key, I would get perpendicular to my first drawn line segment... But instead of that, I get absolute angles.

![image](https://user-images.githubusercontent.com/35814172/224947581-ec30a651-01a7-4adf-a88c-8dabb164a03d.png)

Am I doing something wrong, or is it a bug. I'm really happy with this tool and having this feature working would be an awsome thing!

**Comment by gam17** [comment]
Hi Nejc,
   set AUTOSNAP 4 bit (8 = Turns on polar tracking).
The default value is 55, set to 63 (adding 8).
Let me know...
gam17

**Comment by gam17** [comment]
I think it is fixed
