### ISSUE TITLE
QAD snapping doesn't work on geometries containing either Z or M dimensions

### ISSUE THREAD

**Issue by nydydn** [gam17/QAD#74]
The snapping functionality throws an error when it is supposed to snap to geometries that contain either Z or M dimensions.
The error is:

```
WARNING    Traceback (most recent call last):
              File "C:\Users/***/AppData/Roaming/QGIS/QGIS3\profiles\***/python/plugins\qad\qad_getpoint.py", line 852, in 
              runToggleReferenceLines = lambda: self.toggleReferenceLines(self.__prevGeom, oSnapPoints, self.tmpShiftKey)
              File "C:\Users/***/AppData/Roaming/QGIS/QGIS3\profiles\***/python/plugins\qad\qad_getpoint.py", line 723, in toggleReferenceLines
              self.__QadSnapper.toggleReferenceLines(geom, point, oSnapPointsForPolar, self.__snapMarkerSizeInMapUnits)
              File "C:\Users/***/AppData/Roaming/QGIS/QGIS3\profiles\***/python/plugins\qad\qad_snapper.py", line 403, in toggleReferenceLines
              result = getQadGeomClosestPart(qadGeom, point)
              File "C:\Users/***/AppData/Roaming/QGIS/QGIS3\profiles\***/python/plugins\qad\qad_geom_relations.py", line 4220, in getQadGeomClosestPart
              geomType = qadGeom.whatIs()
             AttributeError: 'NoneType' object has no attribute 'whatIs'
```

Steps to recreate the error on QGIS 3.30:

1. Create scratch layer with "Geometry type: LineString" and Include Z dimension and Include M values ticked
2. Add a new line feature using standard QGIS functionality
3. Save the created feature
4. Start the QAD PLINE command
5. Make sure QAD snapping is active (F3) for at least Segment Start/End
6. Hover the mouse over the line feature created in step 2, as if you'd want to create a new feature starting at one end of the segments of the existing feature.
7. The QAD snapping tooltips don't show up, but instead the above error is thrown

Expected behaviour:
The QAD snapping tooltips would show up and allow the user to start digitizing from snapped position on the geometry.

Current behaviour:
QAD throws the above error.

Notes:
Features created with QAD never contain M or Z coordinates regardless of the set geometry of the layer. This indicates that QAD doesn't support M or Z dimensions in geometries.

Possible solutions:
1. Add Z/M support to QAD feature editing, snapping and wherever else it is relevant
2. Handle the error properly and document lack of Z/M dimensions support in QAD

Workaround:
1. Use "Drop M/Z values" if not needed.
2. Keep this issue open as documentation for lack of Z/M support in QAD

Questions:
1. Is it feasible to add at least Z dimension support in QAD?
2. Is there any interest, even if only on the long-term, of adding such support?

Unfortunately, all I can help with on the short term is testing.

**Comment by gam17** [comment]
Thank you Andrei,
   this is the best report for an issue !
I decided to enable QAD to use layers with z and m values.
Unfortunatly the QAD data model doesn' support z and m values so every object created or modified by QAD will be without such informations.

**Comment by nydydn** [comment]
Unfortunately I missed your response then, so I am coming back to it only now.
Could you please clarify what do you mean by "enable QAD to use layers with z and m values"? Would this mean the error wouldn't show up? or would it show as a proper warning? Or perhaps something else?
As about the QAD model not supporting z values only further confuses the previous statement about qad being able to use layers with z values.
It is unclear to me if there was any change made regarding this issue, or if it hasn't and there are no plans for there to be any in any sense.

Would it be feasible for the support for Z to be limited? as in:
- Z objects to not be created by QAD
- Z objects to be edited by QAD, but ignoring Z, leaving it unchanged
- snapping to Z objects to be enabled, but by ignoring Z, essentially snapping on the XY coordinates of the object.

I am asking beforing delving into it, as I don't know if this would imply changing a couple of ifs, or rewriting the entire core of QAD. If you say it would be closer to the later, I guess it is what it is, and it will be done when it will be done, by whoever might want to do it, whenever they'll need it, but if you estimate that the solution is more towards the former, I could perhaps try to do it myself. I suppose you have an understanding of why Z doesn't simply work, would you mind sharing your technical understanding of the issue?

**Comment by gam17** [comment]
Hi Andrei,
   try the last QAD version  from github, now you can snap on objects with z and m values.
"enable QAD to use layers with z and m values" means that QAD can now read objects from layers with z and m values.
Because its data model supports "2d geometry without m values" only, QAD will not consider Z and M values.
QAD will write data in these layers without z and m values (no warning to the user).
Full support of Z and M values requires rewriting the entire core of QAD. There are no plans to develope such feature actually.
