### ISSUE TITLE
Different Selection Methods not working with Erase command

### ISSUE THREAD

**Issue by ralstogj** [gam17/QAD#76]
Hi

First time using this addin and have only been using QGIS for a month or so. But long time cad users and this looks like a great tool so far.

Have just tried the erase command and then typed H to choose a different selection method have tried a number of those WP,C,W to try and select multipile objects at once. However all seem to fail to find the function to run it. Hopefully it is an easy fix.

Am trying to use on QGis v3. 34.1-Prizren and just added the plugin from the built in plugin wizard.

Regards

Justin Ralston

**Comment by gam17** [comment]
Hi Justin,
   I think I fixed. Can you download the code from github and try ?
Let me know if it works...
gam17
