### ISSUE TITLE
Trace under rightklick meny - error

### ISSUE THREAD

**Issue by APOS80** [gam17/QAD#77]
Shoosing polygon/PLINE, draw first point(or more) and then choosing "trace" in the rightklick menue gives python errors.

Its the same result in both 3.34 and 3.36, trided shape and scratch layers.

![Skärmbild 2024-02-28 150431](https://github.com/gam17/QAD/assets/6387252/ab26b3e9-8110-4e22-8e4d-ce5928396104)

**Comment by gam17** [comment]
Hi Apos80,
   can you try using the code downloaded from github ? It seems already fixed...
