### ISSUE TITLE
Qad error with new QGIS version: 3.34.4-Prizren Prizren, decd43dc

### ISSUE THREAD

**Issue by Voghera** [gam17/QAD#78]
Hi,
I have just installed the new QGIS version "Prizren". Opening a project with a polygon created by Qad in "Firenze" QGIS version, I got the following error:

An error has occurred while executing Python code:

AttributeError: 'QadMapTool' object has no attribute '_QadMapTool__csrRubberBand'
Traceback (most recent call last):
  File "C:\Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_maptool.py", line 234, in canvasMoveEvent
    self.__csrRubberBand.moveEvent(point)
AttributeError: 'QadMapTool' object has no attribute '_QadMapTool__csrRubberBand'

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)]
QGIS version: 3.34.4-Prizren Prizren, decd43dc

Python Path:
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.4\apps\grass\grass83\etc\python
C:\Users\giova\Documents
C:\Program Files\QGIS 3.34.4\bin\python39.zip
C:\PROGRA~1\QGIS33~1.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib
C:\Program Files\QGIS 3.34.4\bin
C:\PROGRA~1\QGIS33~1.4\apps\Python39
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\giova\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
G:/comune_e266u1_master/sviluppo_prof_master/QGIS_totale/addestramento/Gis3

Thanks for your attention.

**Comment by gam17** [comment]
Hi Voghera, I use the LTR 3.22.6 qgis version for developing and testing qad. Something has changed in 3.34.4 version... 
I will install the last QGIS LTR version available to make some tests. QGIS changes too quickly...

**Comment by gam17** [comment]
Can you send me a the QAD version, qgis project with sample data and the description step by step to reproduce the error ?
Thank you

**Comment by Voghera** [comment]
Hi gam17,
now I am back on "Firenze" QGIS version. If I remember well, I got the
following error msg as I opened Qad. If it is not enough, let me know and I
shall install again the 3.34.4-Prizren, decd43dc  QGIS version and try to
trace the operations.
Voghera
------------------------------------------------------------------------------


An error has occurred while executing Python code:

AttributeError: 'QadMapTool' object has no attribute
'_QadMapTool__csrRubberBand'
Traceback (most recent call last):
  File
"C:\Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\
qad\qad_maptool.py", line 234, in canvasMoveEvent
    self.__csrRubberBand.moveEvent(point)
AttributeError: 'QadMapTool' object has no attribute
'_QadMapTool__csrRubberBand'


Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC
v.1929 64 bit (AMD64)]
QGIS version: 3.34.4-Prizren Prizren, decd43dc

Python Path:
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.4/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.4\apps\grass\grass83\etc\python
C:\Users\giova\Documents
C:\Program Files\QGIS 3.34.4\bin\python39.zip
C:\PROGRA~1\QGIS33~1.4\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib
C:\Program Files\QGIS 3.34.4\bin
C:\PROGRA~1\QGIS33~1.4\apps\Python39
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.4\apps\Python39\lib\site-packages\Pythonwin
C:/Users/giova/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\giova\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
G:/comune_e266u1_master/sviluppo_prof_master/QGIS_totale/addestramento/Gis3

**Comment by gam17** [comment]
Hi Voghera, I'm sorry ... it is not enought, I cannot reproduce the error. 
Are you using the github QAD version (let me know the version)?
Can you explain when the error occurs in details?
What do you mean "as I opened QAD" ?
The error occurs when QAD is loaded or when you move the cursor on a feature or something else ?
thank you

**Comment by Voghera** [comment]
Hi,
I have reloaded the Prizren version and I have to work with Qad plugin
active in next hours and days. For the moment I just got one sudden closing
of QGIS without any error msg but in general it is working. I'll you know
if the crash will happen again or not.
Thank you for your help.
Voghera

**Comment by gam17** [comment]
I assume it works now
