### ISSUE TITLE
Distanced offsets not working.

### ISSUE THREAD

**Issue by plaurien** [gam17/QAD#80]
Hello,

First of, the QAD plugin is what makes QGIS meaningful for me so big congrats, you cannot imagine how useful it is :)

Currently, I'm having hard times with the Offset behaviors:
- Draw a line
- click on the QAD offset tool, force a 21m offset
- click on the line to be moved, move the mouse towards the direction of the offset
===> At this point, a correct preview line is made. If I left-click, the final line is moved wherever the mouse pointer was, not where the preview is. (not sure if that changed but I seem to remember that I was left clicking in the past and it worked all fine)
Instead, if I right-click and choose "Enter", the line disappears and nothing is done, it leaves the Offset tool

Sometimes if I choose "Multiple" I'm able to create 2 lines then the next right-click and Enter will delete the last one and maintain the first one.

Am I doing something wrong? Thank in you in advance for your help!

**Comment by gam17** [comment]
Hi plaurien,
   I can reproduce the problem ! I fixed in github version. Can you download and try ?
Let me know if it solves...
Thanks to make QAD a better plugin
gam17

**Comment by plaurien** [comment]
Hello,

Thanks a lot – I just tried and it perfectly works!
Thank YOU so much for making this plugin!

Best regards,
Pierre
