### ISSUE TITLE
QAD - QGIS Maidenhead Problem

### ISSUE THREAD

**Issue by sladepb** [gam17/QAD#82]
TypeError: arguments did not match any overloaded call:   resize(self, a0: QSize): argument 1 has unexpected type 'int'   resize(self, w: int, h: int): argument 2 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/slade.beard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_textwindow.py", line 1166, in onTextChanged
    self.parentWidget().resizeEdits()
  File "C:\Users/slade.beard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_textwindow.py", line 348, in resizeEdits
    self.chronologyEdit.resize(w, chronologyEditHeight)
TypeError: arguments did not match any overloaded call:
  resize(self, a0: QSize): argument 1 has unexpected type 'int'
  resize(self, w: int, h: int): argument 2 has unexpected type 'float'

Python version: 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.36.3-Maidenhead Maidenhead, 2df96554 

Python Path:
E:/Program Files/QGIS 3.36.3/apps/qgis/./python
C:/Users/slade.beard/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/slade.beard/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
E:/Program Files/QGIS 3.36.3/apps/qgis/./python/plugins
E:\Program Files\QGIS 3.36.3\apps\grass\grass83\etc\python
C:\Users\slade.beard\Documents
E:\Program Files\QGIS 3.36.3\bin\python312.zip
E:\Program Files\QGIS 3.36.3\apps\Python312\DLLs
E:\Program Files\QGIS 3.36.3\apps\Python312\Lib
E:\Program Files\QGIS 3.36.3\bin
E:\Program Files\QGIS 3.36.3\apps\Python312
E:\Program Files\QGIS 3.36.3\apps\Python312\Lib\site-packages
E:\Program Files\QGIS 3.36.3\apps\Python312\Lib\site-packages\win32
E:\Program Files\QGIS 3.36.3\apps\Python312\Lib\site-packages\win32\lib
E:\Program Files\QGIS 3.36.3\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/slade.beard/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/OneDrive - EcoThought.com/OneDrive - EcoThought.com/Shared Documents - Lucid - J0137 Facilities Works in Support of Project Phoenix/4. Design Space/InterSite Link/IFT/Riverina/2. Working GIS

**Comment by gam17** [comment]
HI [sladepb](https://github.com/sladepb)
try the updated qad version in github. It should work. Let me know...
From the page https://github.com/gam17/QAD press the button "Code" and then select "Download zip".
The zip contains a folder called "QAD-master". Copy the files contained in that folder into the qad installation folder.
For windows it should be "C:\Users\ \AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qad

**Comment by sladepb** [comment]
Fantastic. That works. Thanks heaps.


Slade Beard

Director

EcoThought Pty Ltd

M 0411137692



ABN 15 125 372 821





"Warning:
The information contained in this email and any attached files is confidential to EcoThought Pty Ltd They may contain proprietary or copyright material or information that is subject to legal professional privilege. They are for the use of the intended recipient only. Any unauthorised viewing, use, disclosure, copying, alteration, storage or distribution of, or reliance on, this message is strictly prohibited. No part may be reproduced, adapted or transmitted without the written permission of the owner. If you have received this transmission in error, or are not an authorised recipient, please immediately notify the sender by return email, delete this message and all copies from your e-mail system, and destroy any printed copies. Receipt by anyone other than the intended recipient should not be deemed a waiver of any privilege or protection.



VIRUS: Every care has been taken to ensure this email and its attachments are virus free, however, any loss or damage incurred in using this email is not the sender's responsibility.  It is your responsibility to ensure virus checks are completed before installing any data sent in this email to your computer."



P
Please consider the environment before printing this e-mail



________________________________
