### ISSUE TITLE
Plugin qad crashed QGIS

### ISSUE THREAD

**Issue by Marga-23** [gam17/QAD#83]
How can I solve this problem? I can't work if I work with the QAD plugin.

Plugin qad crashed QGIS
REPORT
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003c90 (most recent call first):
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_commands.py", line 250 in run
    if QMessageBox.question(None, "QAD", QadMsg.translate("QAD", "QAD plugin is supported by donors. Donations help us to fund software development, documentation, translation and bug-fixing efforts. Do you want to donate ?"), \
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad.py", line 1618 in runCommand
    self.QadCommands.run(command, param)
  File "C:\Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qad\qad_maptool.py", line 196 in canvasPressEvent
    self.plugIn.runCommand("QadVirtualGripCommandsClass", [QadVirtualGripCommandsEnum.STRECTH, \
```

**Stack Trace**

```

QPainter::restore :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::showEvent :
QMessageBox::question :
PyInit_QtWidgets :
PyObject_Call :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
Py_hashtable_compare_direct :
PyObject_Call :
PyObject_Call :
PyInit_sip :
PyInit_sip :
QgsPresetSchemeColorRamp::clone :
QgsMapCanvas::mousePressEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.8-Prizren
QGIS code revision: 91642333
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

**Comment by Marga-23** [comment]
These days I have been testing the program with the QAD plugin, and I have verified that there are a couple of actions that, when executed, cause QGIS to close unexpectedly.
One of them is to try to make the reference to objects 'intersection', and the other is when I make the selection of objects with the QAD plugin (the object, in addition to being marked in yellow, has its vertices marked with the blue square).
From time to time, without performing these actions the program continues to close unexpectedly, but more exceptionally.
I hope this information is useful to be able to solve the problems that the complet presents.
Thank you.

**Comment by gam17** [comment]
Hi,
   Thank you for reporting bugs.
Next week i will try to fix them. 
What do you mean by "to try to make the reference to objects
'intersection'"?

Gam17

**Comment by Marga-23** [comment]
Hello, good morning.

The error that still persists (some have been solved by following the instructions that you have provided to other users), in addition to the fact that the movement of the cursor is slowed down and that it moves in jumps and not with a continuous movement (I think this is not I commented previously), is that when I use intersection in object references, the program crashes and in 90% of cases it closes suddenly.

I hope I have clarified the error that occurs in QGIS with the QAD plugin.

Thank you so much.

**Comment by gam17** [comment]
HI Marga-23,
   sorry for the delay. Can you send me a simple qgis projects with a small data set to reproduce your issue ? Describe, if possible, the operations I have to do to reproduce the error (step by step).
Thanks for your patience
gam17

**Comment by gam17** [comment]
Hi, can you test the last github version (download the zip file) ?
let me know if it solves...
gam17

**Comment by gam17** [comment]
We do our best to fix bugs or unexpected issues but we need your collaboration.
If you don't answer or provide informations we are asking for, it will be impossible to solve the case.
Thank you for your collaboration.
