### ISSUE TITLE
Zoom isn't working when using QAD

### ISSUE THREAD

**Issue by patricev** [gam17/QAD#9]
Hi devteam, 

You've created a very usefull app. thanks !
I'm on windows 7 and QGis 2.16.3. The zoom (scroll wheel) works when I edit something, but when editing is finished, the zoom doesn't work. Is it normal ?
Regards,
Patrice Verchere

**Comment by patricev** [comment]
Hi
I find the issue - in qad_mapttool change wheelEvent like this :

```
def wheelEvent(self, event):
    zoomfactor = 2.0
    r = self.canvas.mapSettings().extent()
    center = r.center()
    point = self.toMapCoordinates(event.pos())
    if event.delta()>0:   #zoom in
        zoomfactor = 1/zoomfactor
    newcenter = QgsPoint(point.x() + (center.x() - point.x() ) *zoomfactor, point.y() + (center.y() - point.y()  ) *zoomfactor )
    r.scale(zoomfactor, newcenter )
    self.canvas.setExtent(r)
    self.__csrRubberBand.moveEvent(self.toMapCoordinates(event.pos()))
    self.canvas.refresh()

```

**Comment by gam17** [comment]
It worked fine until qgis 2.14. You are right ! The qgis core team has changed something about wheel event. Thank you for searching a solution !
I think the best solution is:
 def wheelEvent(self, event):
      QgsMapTool.wheelEvent(self, event)
      self.__csrRubberBand.moveEvent(self.toMapCoordinates(event.pos()))

I am using the last ltr qgis version (2.14). I will upload this fix in the next relase of QAD.
Thak you for your collaboration.
